# Site
repository: jamleekim/jamleekim.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김재민
title: 자바&스프링 기반 Backend Developer
email: slam67@naver.com

# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jamleekim
linkedin_username: jaemin-kim-developer

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  <mark>Java & Spring</mark> 기반의 4년차 백엔드 개발자로 LG CNS에서 API/Batch 및 어드민 페이지 개발 및 운영을 해왔습니다.
  
  U+, kb국민은행, ebay korea, 레드캡투어와 같이 여러 도메인을 가진 회사의 프로젝트를 경험하였으며,

  MSA, DevOps, AWS에 관심을 가지고 있습니다.

  - 아주대학교 졸업 (2013.03 - 2019.02)
  
  - 복수전공 미디어학 & 소프트웨어학

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 사내 내부 계약 관리 대시보드
        caption: 2021.9 ~ 현재
        description: | 
            - JSP, Spring boot, JPA, MariaDB
            - 사내 wire 계정 SSO와 연동하여 Spring Security 적용
            - AWS EC2, S3, RDS 활용하여 Cloud에서 운영
            - Travis CI 활용 CI 구축
      - layout: left
        sub_title: 상용UI소스 정적분석 도구
        caption: 2021.5 ~ 2021.12
        description: | 
            - JSP, Spring, MariaDB
            - Dom Parser, Sax Parser 활용
            - UI 소스 분석 태그 내 속성 파싱, 오기입 추출
      - layout: left
        sub_title: 레드캡투어 차세대
        caption: 2020.3 ~ 2021.4
        description: | 
            - Angular, Typescript, Spring boot, Spring batch, Redis, Oracle
            - SMS/카카오톡 일단위 메시징 배치 프로그램 개발 및 설계
            - Angular 기반 어드민 페이지 개발 및 운영
            - Redis 적용, 항공/호텔 검색속도 개선
            - i18n 적용, 다국어 기능 제공
      - layout: left
        sub_title: 이베이코리아 직매입시스템 구축
        caption: 2020.1 ~ 2020.3
        description: | 
            - Vue, Spring Boot, MySql
            - MSA기반 매입 관련 API 개발
      - layout: left
        sub_title: KB MVNO 금융-통신 융합서비스 시스템 구축
        caption: 2019.7 ~ 2019.12
        description: | 
            - Apache Camel, Spring, Oracle
            - 스프링 기반 메인프레임, U+서버 연계 목적 인터페이스 개발
      - layout: left
        sub_title: U+ shop 차세대프로젝트
        caption: 2019.3 ~ 2019.7
        description: | 
            - JSP, Spring boot, Oracle
            - 상품/MMS 관련 배치 프로그램 개발 및 설계                             
  - title: 기술 스택
    layout: list
    content:
      - layout: left
        title: Angular
        description: |
            UI 컴포넌트 설계 및 구현이 가능하고, Ngrx를 통해 조건에 따라 빈번하게 바뀌는 UI를 제어할 수 있습니다.
            컴포넌트 기반의 효율적인 상태 관리를 추구합니다.
      - layout: left
        title: Javascript
        description: |
            적절한 자료구조가 필요할 땐 Lodash와 Underscore를 활용하고 JavaScript 프레임워크들을 적극 사용합니다. 객체와 메소드 중심의 개발보다 함수형 프로그래밍을 좋아합니다.
      - layout: left
        title: Spring
        description: |
            백엔드 애플리케이션 구현 시 주로 사용하며, Spring Batch, Spring Security, Spring Data JPA, JUnit, Maven 등을 활용하여, 
            설계서 기반의 기능 구현이 가능합니다. 
      - layout: left
        title: Git
        description: |
            로컬과 리모트 저장소를 나누어 작업이 가능하며, pull request를 통해 코드 리뷰를 진행합니다. 
            긴급 반영 시 hotfix 브랜치를 생성하여 머지하는 방식으로 소스를 관리합니다.
      - layout: left
        title: AWS
        description: |
            EC2 인스턴스를 설정하여, spring 프로젝트를 배포하고 관리 할 수 있습니다. 
            S3를 활용하여 정적리소스틀 관리, 요청 시 필요한 리소스를 내려받을 수 있습니다.
            RDS를 활용하여 MariaDB를 구축, 운영 데이터를 관리 및 운영할 수 있습니다.
  
  - title: 학부 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 파란학기-우리동네동호회
        caption: 2016.07 ~ 2016.12
        quote: >
          jQuery, jsp, Spring, Mysql
        description: | 
          학부에서 진행했던 파란 학기 제도를 이용해 학생 스스로 설계한 도전과제를 심의받아 학점으로 인정받는 활동을 한 경험 이있습니다. 
          실제 국내 생활 체육 동호회 활동에 필요한 웹앱을 기획, 제작까지 경험해 볼 수 있었습니다.
          동호회 관리 사업자의 요구사항을 기반으로 기획, 분석및 설계를 진행하였으며, 도메인 기반의 설계서 작성과 더불어 Agile 방법론을 도입, 2번의 iteration을 나누어 작업을 진행하였습니다.
      - layout: left
        title: 도서관리 QR인증 앱
        caption: 2017.03 ~ 2017. 06
        quote: >
          Android Studio, Java, Python, Rest API
        description: | 
          동아리방에서 사용 가능한 도서관리 안드로이드 앱을 제작하였습니다. 
          현재 코로나로 인해 자주 사용되고 있는 카카오 QR코드 인증방식과 유사한 도서별로 QR코드 마커를 제작, 
          앱에서 코드 스캔 시 사용자 인증과 대출 기록이 관리되도록 하는 방식을 고안하였습니다. 
          로그인은 JWT방식으로 구현하여 로그인된 사용자에 한하여 사용자인증과 대출 기능이 동작하도록 작업하였습니다.
      - layout: left
        title: 블록체인 기반 게임 
        caption: 2018.07 ~ 2018.12
        quote: >
          DApp, Solidity, Truffle Framework, Ganache, React
        description: | 
          졸업작품으로는 블록체인 플랫폼을 이용한 게임제작을 진행하였습니다. 
          DApp개발을 위해 블록체인 플랫폼의 스마트 계약을 작성, 구현하기 위하여 Solidity 언어를 사용하였습니다. 
          개발 시 솔리디티 코드를 로컬 환경에서 보다 쉽게 컴파일, 배포하기 위하여 Truffle Framework를 사용하였습니다. 
          개발 단계에서 실제 이더리움 없이 시뮬레이션 테스트 환경을 구성하기 이하여 Ganache를 이용, 
          트랜잭션을 생성시켜 테스트를 진행하였습니다.


#      Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
