# Site
repository: jamleekim/jamleekim.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김재민
title: 자바&스프링 기반 Backend Developer
email: jamleekim67@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jamleekim
linkedin_username: jaemin-kim-developer

# About Section
# about_title: About Me
about_profile_image: images/profile_image.jpeg
about_content: | # this will include new lines to allow paragraphs
  <mark>Java & Spring</mark> 기반의 4년차 백엔드 개발자로 LG CNS에서 API/Batch 및 어드민 페이지 개발 및 운영을 해왔습니다.
  
  U+, kb국민은행, ebay korea, 레드캡투어와 같이 여러 도메인을 가진 회사의 프로젝트를 경험하였으며,

  MSA, DevOps, AWS에 관심을 가지고 있습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 사내 내부 계약 관리 대시보드
        caption: 2021.9 ~ 현재
        description: | 
            - JSP, Spring boot, JPA, MariaDB
            - 사내 wire 계정 SSO와 연동하여 Spring Security 적용
            - AWS EC2, S3, RDS 활용하여 Cloud에서 운영
            - Travis CI 활용 CI 구축
      - layout: left
        sub_title: 상용UI소스 정적분석 도구
        caption: 2021.5 ~ 2021.12
        description: | 
            - JSP, Spring, MariaDB
            - Dom Parser, Sax Parser 활용
            - UI 소스 분석 태그 내 속성 파싱, 오기입 추출
      - layout: left
        sub_title: 레드캡투어 차세대
        caption: 2020.3 ~ 2021.4
        description: | 
            - Angular, Typescript, Spring boot, Spring batch, Oracle
            - SMS/카카오톡 일단위 메시징 배치 프로그램 개발 및 설계
            - Angular 기반 어드민 페이지 개발 및 운영
      - layout: left
        sub_title: 이베이코리아 직매입시스템 구축
        caption: 2020.1 ~ 2020.3
        description: | 
            - Vue, Spring Boot, MySql
            - MSA기반 매입 관련 API 개발
      - layout: left
        sub_title: KB MVNO 금융-통신 융합서비스 시스템 구축
        caption: 2019.7 ~ 2019.12
        description: | 
            - Apache Camel, Spring, Oracle
            - 스프링 기반 메인프레임, U+서버 연계 목적 인터페이스 개발
      - layout: left
        sub_title: U+ shop 차세대프로젝트
        caption: 2019.3 ~ 2019.7
        description: | 
            - JSP, Spring boot, Oracle
            - 상품/MMS 관련 배치 프로그램 개발 및 설계                             

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아주대학교
        caption: 2013.03 - 2019.02
        sub_title: 미디어학 & 소프트웨어학
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
